type Diagnostico {
  diagnostico1: String!
}

enum DiagnosticoEnum {
  CodigoHemoptisis
  CodigoViaAerea
  CodigoInfarto
  COVID
  Influenza
  Parainfluenza
  Adenovirus
  VirusSincialRespiratorio
  TuberculosisSensible
  TuberculosisResistente
  B24
  SIRA
  NeumoniaBacteriana
  EPOC
  Asma
  TromboembiaPulmonar
  DerramePleural
  Neumotorax
  NeumoniaIntersticialDifusa
  InsuficienciaCaridiaca
  CaPulmonarOSospecha
}